when@dev:
    web_profiler:
        toolbar: true
    framework:
        profiler: { only_exceptions: true }

when@test:
    web_profiler:
        toolbar: false

    framework:
        profiler: { collect: false }

when@prod:
    web_profiler:
        toolbar: false

    framework:
        profiler: { collect: false }


