index:
    path: /
    controller: App\Controller\ArticleController::list

# Inutile avec utilisation des annotations @Route dans les commentaires
# use Symfony\Component\Routing\Annotation\Route
# ---------------------------------------------------------------------

app_home:
    path: /
    controller: App\Controller\ArticleController::list
app_article_list:
    path: /app_article_list
    controller: App\Controller\ArticleController::list
app_article_new:
    path: /app_article_new
    controller: App\Controller\ArticleController::new
app_source_new:
        path: /app_source_new
        controller: App\Controller\SourceController::new
