parameters:
    url_zoho            : 'https://www.zohoapis.eu'
#    zoho_zapikey        : '1003.540059245b5e7ae0eb44abbb0673121e.2635772b1ab9e2399085c2301f6ed472'
    zoho_zapikey        : '1003.d92d72b3be3493720cd4c269ecea8378.288077dd25ea0e0dc8ab61e252042659'
    url_ogone           : 'https://secure.ogone.com/ncol/prod/orderstandard.asp'
    ogone_pspid         : 'ATALANTE'
    ogone_psw           : 'Motdepasse220895!'
    ogone_sha_in        : 'lLoW$Ri.Ts&6aq#7+/65m8(!oV4soI'
    ogone_sha_out       : 'L6K#Q22EQ.1C1_?_wpC3iGRorq-XH6'
    ogone_sha           : 'sha1'
#    ogone_template      : 'https://logos.tourism-it.com/atalante/modele.html'
    ogone_template      : 'https://logos.tourism-it.com/media/ogone/atalante/2023/modele.html'