parameters:

services:

    App\Service\ArticleAgregator:


    #    App\Service\DatabaseService:
    #       arguments:
    #            $dsn: '%env(DATABASE_DSN)%'
    #            $user: '%env(DATABASE_USER)%'
    #            $password: '%env(DATABASE_PASSWORD)%'

    App\Service\SourceService:
        arguments:
            $dsn: '%env(DATABASE_DSN)%'
            $user: '%env(DATABASE_USER)%'
            $password: '%env(DATABASE_PASSWORD)%'